# Generated by Django 2.0 on 2019-01-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='oreder_desc',
            field=models.CharField(max_length=120),
        ),
    ]
